### ISSUE TITLE
GUI options

### ISSUE THREAD

**Issue by jsdevel** [wjasper/Linux_Drivers#21]
hello, and thanks for creating this library!

i was successfully able to install the driver and run the test program (i'm on fedora 29).  i'm wondering how i can interface with the board via a gui.  i realize this is likely outside the purview of this project, but was thinking someone here would likely know (others likely have similar questions).

**Comment by lucasw** [comment]
Take any gui code that is in the same language as example code here and put the the example code from here into it.  Instead of converting values from scanf the value would come from the gui.  For the pci drivers the language doesn't really matter as long it is possible to do the equivalent of open() and read() and write().

**Comment by wjasper** [comment]
I want to second what Lucas said.  There are many options for a gui, and for that reason I have not forced a particular gui option with the library.  Best to take a GUI API in either C/C++ or Python and 
wrap that (via the callbacks in the GUI) from my example code.
